[phases.setup]
aptPkgs = ["python3", "python3-dev", "python3-pip", "curl"]

[phases.install]
cmds = [
  "curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "python3 get-pip.py",
  "pip3 install --upgrade pip",
  "pip3 install -r requirements.txt"
]

[start]
cmd = "python3 -m streamlit run app.py" 