[phases.setup]
aptPkgs = ["python3", "python3-venv", "python3-pip"]

[phases.install]
cmds = [
  "python3 -m venv .venv",
  "source .venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

[start]
cmd = "source .venv/bin/activate && streamlit run --server.address 0.0.0.0 --server.port $PORT --logger.level debug app.py" 