[phases.setup]
nixPkgs = ["python39", "gcc", "python39Packages.pip", "python39Packages.virtualenv"]

[phases.install]
cmds = [
  "python -m venv .venv",
  "source .venv/bin/activate",
  "pip install -r requirements.txt"
]

[start]
cmd = "streamlit run app.py" 