[phases.setup]
aptPkgs = ["python3", "python3-pip"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "streamlit run --server.address 0.0.0.0 --server.port $PORT --logger.level debug app.py" 