[build]
builder = "nixpacks"

[deploy]
startCommand = "python3 -m streamlit run app.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[deploy.env]
PORT = "8501"
STREAMLIT_SERVER_PORT = "8501"
PYTHONUNBUFFERED = "1" 