[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
startCommand = "streamlit run app.py"

[deploy.env]
PORT = "8501"
STREAMLIT_SERVER_PORT = "8501"
STREAMLIT_SERVER_ADDRESS = "0.0.0.0"
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_FILE_WATCHER_TYPE = "none"
GOOGLE_API_KEY = "[REDACTED_GOOGLE_API_KEY]" 