[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["/"]

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 480
restartPolicyType = "on_failure"
# 用 $PORT！！不要写死8501，不要加 PORT 环境变量
startCommand = "/app/.venv/bin/streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --logger.level debug"

[deploy.env]
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_FILE_WATCHER_TYPE = "none"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"
GOOGLE_API_KEY = "[REDACTED_GOOGLE_API_KEY]"
