[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"
watchPaths = ["/"]

[deploy]
healthcheckPath = "/_stcore/health"
healthcheckTimeout = 480
restartPolicyType = "on_failure"
startCommand = "sh -c \".venv/bin/streamlit run app.py --server.address 0.0.0.0 --server.port $PORT --logger.level debug\""

[deploy.env]
STREAMLIT_SERVER_HEADLESS = "true"
STREAMLIT_SERVER_FILE_WATCHER_TYPE = "none"
STREAMLIT_SERVER_ENABLE_CORS = "false"
STREAMLIT_SERVER_ENABLE_XSRF_PROTECTION = "false"
# GOOGLE_API_KEY 不应硬编码到仓库中，请在部署平台环境变量中配置
# GOOGLE_API_KEY = ""
